/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArithmeticJNI */

#ifndef _Included_ArithmeticJNI
#define _Included_ArithmeticJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ArithmeticJNI
 * Method:    add
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_ArithmeticJNI_add
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     ArithmeticJNI
 * Method:    subtract
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_ArithmeticJNI_subtract
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     ArithmeticJNI
 * Method:    multiply
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_ArithmeticJNI_multiply
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     ArithmeticJNI
 * Method:    divide
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_ArithmeticJNI_divide
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
